version: "3.1"

services:
    nginx:
        build: 
            context: ./docker/nginx
        ports:
            - 80:80
        volumes:
            - ./src/mediawiki:/var/www/html:ro
        networks:
            - server
        depends_on:
            - php
    php:
        build: 
            context: ./docker/php
        expose:
            - 9000
        volumes:
            - ./src:/var/www/html
        networks:
            - server
            - database
        depends_on:
            - mysql
    mysql:
        build: 
            context: ./docker/mysql
        environment:
            - MYSQL_DATABASE=phpmyadmin
            - MYSQL_USER=phpmyadmin
            - MYSQL_PASSWORD=phpmyadmin
            - MYSQL_ROOT_PASSWORD=secret  

        networks:
            - database
        volumes:
            - ./docker/mysql/phpmyadmin.sql:/docker-entrypoint-initdb.d/phpmyadmin.sql
            - persistent:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            #PMA_ARBITRARY: 1
            PMA_HOST: mysql 
        ports:
            - 8080:80
        networks:
            - database    
        volumes:
            #- /sessions
            - ./docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
            #- /custom/phpmyadmin/theme/:/www/themes/theme/        
networks:
    database:
    server:
volumes:
    persistent: