version: "3.1"

services:
    nginx:
        build: 
            context: ./docker/nginx
        ports:
            - 80:80
        volumes:
            - ./src:/var/www/html:ro
        networks:
            - server
        depends_on:
            - php
    php:
        build: 
            context: ./docker/php
        expose:
            - 9000
        volumes:
            - ./src:/var/www/html
        networks:
            - server
            - database
        depends_on:
            - mysql
    mysql:
        build: 
            context: ./docker/mysql
        environment:
            - MYSQL_DATABASE=mydb
            - MYSQL_USER=myuser
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=docker
        expose:
            - 3306
        networks:
            - database
        volumes:
            - ./docker/mysql/data.sql:/docker-entrypoint-initdb.d/data.sql
            - persistent:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        networks:
            - database
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql    
networks:
    database:
    server:
volumes:
    persistent: